name: PHP Linting
on:
  push:
    branches: ["master"]
  pull_request:
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          pintVersion: 1.8.0
          onlyDirty: true
